name: pytest

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: '3.8'
            mlflow: '2.0.1' # Earliest MLflow 2.X
            pyspark: '3.0.3' # Earliest PySpark 3.X
            java: '11'
          - python: '3.11'
            mlflow: '2.22.4' # Latest MLflow 2.X
            pyspark: '3.5.8' # Latest PySpark 3.X
            java: '11'
          - python: '3.13'
            mlflow: '3.0.0' # Earliest MLflow 3.X
            pyspark: '4.0.2' # Earliest PySpark 4.X
            java: '17'
          - python: '3.13'
            mlflow: '3.10.1' # Latest MLflow 3.X
            pyspark: '4.1.1' # Latest PySpark 4.X
            java: '17'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        cache: 'pip'
    - run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install mlflow==${{ matrix.mlflow }}
        pip install pyspark==${{ matrix.pyspark }}
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - run: |
        python -m pytest
